[workspace]
members = ["cadet", "rocketman", "types"]
resolver = "2"


[workspace.dependencies]
# main binary
cadet = { path = "./cadet" }
# jetstream library
rocketman = { path = "./rocketman" }
# types library
types = { path = "./types" }

serde = "1"
serde_json = "1"
