services:
  cadet:
    image: ghcr.io/espeon/cadet
    ports:
      - "9000:9000"
    env_file:
      - .env
  satellite:
    image: ghcr.io/espeon/satellite
    ports:
      - "3132:3000"
    env_file:
      - .env
