[package]
name = "cadet"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "time"] }
tokio-tungstenite = { version = "0.20", features = [
    "rustls-tls-native-roots",
    "rustls-tls-webpki-roots",
] }
futures-util = "0.3"
url = "2.0"
rand = "0.8"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
metrics = "0.24.1"
metrics-exporter-prometheus = "0.16.2"
anyhow = "1.0.95"

tealstream.workspace = true
flume = "0.11.1"
async-trait = "0.1.86"
